GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/657fb0b0befb5803749940c8

###

POST http://localhost:3000/subscribers
Content-Type: application/json
    
{
    "name": "Amazing Spiderman",
    "subscribedToChannel": "Web Dev Simplified"
}

###

DELETE http://localhost:3000/subscribers/657fb0b0befb5803749940c8

###

PATCH http://localhost:3000/subscribers/657fb0b0befb5803749940c8
Content-Type: application/json

{
    "name": "New Name zzzzZZZzzz"
}
